In [19]:
using HomotopyContinuation
using LinearAlgebra

In [13]:
x = 10
x + 1
f(x) = 2x
f(3)
δ = 3 # tabs after latex
typeof("My string")
function myfun(x,y)
    x + y
end
zeros(3)
ones(2)
methods(Bool

UndefVarError: UndefVarError: I not defined

In [10]:
link_lengths = [0.5,0.2,0.3,0.4]


4-element Array{Float64,1}:
 0.5
 0.2
 0.3
 0.4

In [37]:
@polyvar p[1:4,1:2]

(DynamicPolynomials.PolyVar{true}[p₁₋₁ p₁₋₂; p₂₋₁ p₂₋₂; p₃₋₁ p₃₋₂; p₄₋₁ p₄₋₂],)

In [73]:
q = vec(sum(p .* p, dims=2) .- 1)


4-element Array{DynamicPolynomials.Polynomial{true,Int64},1}:
 p₁₋₁² + p₁₋₂² - 1
 p₂₋₁² + p₂₋₂² - 1
 p₃₋₁² + p₃₋₂² - 1
 p₄₋₁² + p₄₋₂² - 1

In [55]:
#r = sum((p[2:4,:] .- p[1:3,:]).^2,dims=2) - link_lengths[2:4]

3×1 Array{DynamicPolynomials.Polynomial{true,Float64},2}:
 p₁₋₁² - 2.0p₁₋₁p₂₋₁ + p₂₋₁² + p₁₋₂² - 2.0p₁₋₂p₂₋₂ + p₂₋₂² - 0.2
 p₂₋₁² - 2.0p₂₋₁p₃₋₁ + p₃₋₁² + p₂₋₂² - 2.0p₂₋₂p₃₋₂ + p₃₋₂² - 0.3
 p₃₋₁² - 2.0p₃₋₁p₄₋₁ + p₄₋₁² + p₃₋₂² - 2.0p₃₋₂p₄₋₂ + p₄₋₂² - 0.4

In [65]:
end_position = [-0.5, .7]

2-element Array{Float64,1}:
 -0.5
  0.7

In [72]:
r = vec(sum(reshape(link_lengths, (4,1)) .* p,dims=1)) - end_position #- reshape(end_position,(1,2))

2-element Array{DynamicPolynomials.Polynomial{true,Float64},1}:
 0.5p₁₋₁ + 0.2p₂₋₁ + 0.3p₃₋₁ + 0.4p₄₋₁ + 0.5
 0.5p₁₋₂ + 0.2p₂₋₂ + 0.3p₃₋₂ + 0.4p₄₋₂ - 0.7

In [87]:
#constraints = vcat(q,r, dot(rand(8), vec(p)), dot(rand(8), vec(p)) )
constraints = vcat(q,r, p[1,1]+1, p[1,2] )

8-element Array{DynamicPolynomials.Polynomial{true,Float64},1}:
 p₁₋₁² + p₁₋₂² - 1.0                        
 p₂₋₁² + p₂₋₂² - 1.0                        
 p₃₋₁² + p₃₋₂² - 1.0                        
 p₄₋₁² + p₄₋₂² - 1.0                        
 0.5p₁₋₁ + 0.2p₂₋₁ + 0.3p₃₋₁ + 0.4p₄₋₁ + 0.5
 0.5p₁₋₂ + 0.2p₂₋₂ + 0.3p₃₋₂ + 0.4p₄₋₂ - 0.7
 p₁₋₁ + 1.0                                 
 p₁₋₂                                       

In [89]:
real_solutions(solve(constraints))

2-element Array{Array{Float64,1},1}:
 [-1.0, 0.968246, 3.0965e-15, -0.484123, 1.55882e-21, 0.25, 1.0, 0.875]  
 [-1.0, -0.968246, 8.88279e-15, 0.484123, -1.45501e-21, 0.25, 1.0, 0.875]

Hmm. Randomly using linear cuts did not do what I was hoping. Maybe I could add an optimization criteria. closeness to other control points. just constraining the arm to go to the left worked
Optics with polynomials.
Iso surface starting positiion. S(x)=0 
(x1-x2)^2 + (y1-y2)^2 = d
d(x,x') = (x1-x2)^2 + (y1-y2)^2
partial(d,x)
